module.exports = {
  plugins: ["jest"],
  rules: {
    "jest/no-disabled-tests": "warn",
    "jest/no-focused-tests": "error",
    "jest/no-identical-title": "error",
    "jest/valid-expect": "error",
    "jest/no-alias-methods": "off",
    "jest/no-jest-import": "error",
    "jest/no-large-snapshots": ["warn", { maxSize: 300 }],
    "jest/no-test-prefixes": "error",
    "jest/prefer-to-contain": "warn",
    "jest/prefer-to-have-length": "warn",
    "jest/valid-describe": "error",
    "jest/valid-expect-in-promise": "error",
    "jest/consistent-test-it": "off",
    "jest/lowercase-name": "off",
    "jest/no-hooks": "off",
    "jest/no-jasmine-globals": "off",
    "jest/no-test-callback": "off",
    "jest/prefer-expect-assertions": "off",
    "jest/prefer-to-be-null": "off",
    "jest/prefer-to-be-undefined": "off",
    "jest/require-tothrow-message": "off",
    "jest/expect-expect": "warn",
    "jest/no-test-return-statement": "warn",
    "jest/prefer-inline-snapshots": "off",
    "jest/prefer-strict-equal": "off",
    "jest/prefer-spy-on": "off",
    "jest/no-commented-out-tests": "warn",
    "jest/no-empty-title": "off",
    "jest/no-mocks-import": "error",
    "jest/no-truthy-falsy": "off",
    "jest/prefer-called-with": "off",
    "jest/prefer-todo": "error",
    "jest/no-duplicate-hooks": "error",
    "jest/no-export": "error",
    "jest/no-if": "error",
    "jest/no-standalone-expect": "error",
    "jest/no-try-expect": "error",
    "jest/no-expect-resolves": "warn",
    "jest/require-to-throw-message": "off",
    "jest/prefer-hooks-on-top": "off",
    "jest/require-top-level-describe": "error",
    "jest/valid-title": "off",
  },
  env: {
    "jest/globals": true,
  },
};
